/* Distributed under the OSI-approved BSD 3-Clause License.  See accompanying
   file LICENSE.rst or https://cmake.org/licensing for details.  */

#include "cmGlobalRedoGenerator.h"

#include <algorithm>
#include <cstddef>
#include <string>
#include <utility>
#include <vector>

#include <cm/memory>

#include <cmsys/Glob.hxx>

#include "cmDocumentationEntry.h"
#include "cmGeneratedFileStream.h"
#include "cmGeneratorTarget.h"
#include "cmLocalGenerator.h"
#include "cmMakefile.h"
#include "cmState.h"
#include "cmStringAlgorithms.h"
#include "cmSystemTools.h"
#include "cmake.h"

#include "cmLocalRedoGenerator.h"

namespace {

std::string QuoteForSh(std::string const& s)
{
  std::string out;
  out.reserve(s.size() + 2);
  out.push_back('\'');
  for (char c : s) {
    if (c == '\'') {
      out.append("'\\''");
    } else {
      out.push_back(c);
    }
  }
  out.push_back('\'');
  return out;
}

void EmitRedoIfchange(std::vector<std::string>& lines,
                      std::vector<std::string> const& deps,
                      std::size_t maxArgsPerLine = 128)
{
  if (deps.empty()) {
    return;
  }

  std::size_t i = 0;
  while (i < deps.size()) {
    std::string cmd = "redo-ifchange";
    std::size_t n = 0;
    for (; i < deps.size() && n < maxArgsPerLine; ++i, ++n) {
      cmd.push_back(' ');
      cmd.append(QuoteForSh(deps[i]));
    }
    lines.emplace_back(std::move(cmd));
  }
}

void WriteDoFile(std::string const& path, std::vector<std::string> const& lines)
{
  cmSystemTools::MakeDirectory(cmSystemTools::GetFilenamePath(path));
  cmGeneratedFileStream file(path);
  file.SetCopyIfDifferent(true);
  for (auto const& line : lines) {
    file << line << '\n';
  }
}

} // namespace

cmGlobalRedoGenerator::cmGlobalRedoGenerator(cmake* cm)
  : cmGlobalCommonGenerator(cm)
{
  this->FindMakeProgramFile = "CMakeRedoFindMake.cmake";
  cm->GetState()->SetIsGeneratorMultiConfig(false);
}

std::unique_ptr<cmGlobalGeneratorFactory> cmGlobalRedoGenerator::NewFactory()
{
  return std::unique_ptr<cmGlobalGeneratorFactory>(
    new cmGlobalGeneratorSimpleFactory<cmGlobalRedoGenerator>());
}

cmDocumentationEntry cmGlobalRedoGenerator::GetDocumentation()
{
  return { cmGlobalRedoGenerator::GetActualName(),
           "Generates redo .do scripts." };
}

void cmGlobalRedoGenerator::Generate()
{
  // Execute the standard generate process (drives local generators).
  cmGlobalGenerator::Generate();

  if (cmSystemTools::GetErrorOccurredFlag()) {
    return;
  }

  std::string const topBinary = this->GetCMakeInstance()->GetHomeOutputDirectory();

  // Collect logical targets that produce a build artifact.
  std::vector<std::string> allTargets;
  for (auto const& lg : this->GetLocalGenerators()) {
    for (auto const& gt : lg->GetGeneratorTargets()) {
      if (!gt->IsInBuildSystem()) {
        continue;
      }
      switch (gt->GetType()) {
        case cmStateEnums::EXECUTABLE:
        case cmStateEnums::SHARED_LIBRARY:
        case cmStateEnums::STATIC_LIBRARY:
        case cmStateEnums::MODULE_LIBRARY:
          // Best-effort: respect EXCLUDE_FROM_ALL as a boolean.
          if (gt->GetPropertyAsBool("EXCLUDE_FROM_ALL")) {
            continue;
          }
          allTargets.emplace_back(gt->GetName());
          break;
        default:
          break;
      }
    }
  }
  std::sort(allTargets.begin(), allTargets.end());
  allTargets.erase(std::unique(allTargets.begin(), allTargets.end()),
                   allTargets.end());

  // all.do
  {
    std::vector<std::string> lines;
    lines.emplace_back("# Generated by CMake Redo generator.");
    lines.emplace_back(cmStrCat("cd ", QuoteForSh(topBinary)));
    EmitRedoIfchange(lines, allTargets);
    lines.emplace_back(": >\"$3\"");
    WriteDoFile(cmStrCat(topBinary, "/all.do"), lines);
  }

  // install.do
  {
    std::vector<std::string> lines;
    lines.emplace_back("# Generated by CMake Redo generator.");
    lines.emplace_back(cmStrCat("cd ", QuoteForSh(topBinary)));
    lines.emplace_back("redo-ifchange all");
    std::string const cmakeCommand = cmSystemTools::GetCMakeCommand();
    lines.emplace_back(
      cmStrCat(QuoteForSh(cmakeCommand), " -P ", QuoteForSh("cmake_install.cmake")));
    lines.emplace_back(": >\"$3\"");
    WriteDoFile(cmStrCat(topBinary, "/install.do"), lines);
  }

  // clean.do (minimal): remove top-level stamps and known target output files.
  {
    std::vector<std::string> outputs;
    for (auto const& lg : this->GetLocalGenerators()) {
      for (auto const& gt : lg->GetGeneratorTargets()) {
        if (!gt->IsInBuildSystem()) {
          continue;
        }
        switch (gt->GetType()) {
          case cmStateEnums::EXECUTABLE:
          case cmStateEnums::SHARED_LIBRARY:
          case cmStateEnums::STATIC_LIBRARY:
          case cmStateEnums::MODULE_LIBRARY: {
            std::string const outAbs =
              gt->GetFullPath("", cmStateEnums::RuntimeBinaryArtifact, true);
            outputs.emplace_back(cmSystemTools::RelativePath(topBinary, outAbs));
          } break;
          default:
            break;
        }
      }
    }
    std::sort(outputs.begin(), outputs.end());
    outputs.erase(std::unique(outputs.begin(), outputs.end()), outputs.end());

    std::vector<std::string> lines;
    lines.emplace_back("# Generated by CMake Redo generator.");
    lines.emplace_back(cmStrCat("cd ", QuoteForSh(topBinary)));
    for (auto const& t : allTargets) {
      lines.emplace_back(cmStrCat("rm -f ", QuoteForSh(t)));
    }
    for (auto const& o : outputs) {
      lines.emplace_back(cmStrCat("rm -f ", QuoteForSh(o)));
    }
    lines.emplace_back("rm -f all install clean");
    lines.emplace_back(": >\"$3\"");
    WriteDoFile(cmStrCat(topBinary, "/clean.do"), lines);
  }

  // Best-effort progress plan: enumerate all generated .do scripts and write a
  // stable "total steps" manifest for redo-log. This helps redo-log show a
  // Ninja-like [done/total] counter for `redo all` even on the first build.
  //
  // The manifest lists *target outputs* (not the .do scripts themselves),
  // expressed as paths relative to the build tree root.
  {
    cmsys::Glob g;
    g.SetRecurse(true);
    g.SetListDirs(false);
    g.SetRelative(topBinary.c_str());
    // Recurse through the build tree and find all *.do scripts.
    g.FindFiles(cmStrCat(topBinary, "/*.do"));
    std::vector<std::string> outs;
    outs.reserve(g.GetFiles().size());
    for (auto const& doRel : g.GetFiles()) {
      if (!cmHasSuffix(doRel, ".do")) {
        continue;
      }
      // Map "foo.do" -> "foo" (target output path).
      outs.emplace_back(doRel.substr(0, doRel.size() - 3));
    }
    std::sort(outs.begin(), outs.end());
    outs.erase(std::unique(outs.begin(), outs.end()), outs.end());

    std::string const redoDir = cmStrCat(topBinary, "/.redo");
    cmSystemTools::MakeDirectory(redoDir);
    std::string const planPath = cmStrCat(redoDir, "/plan.targets");
    cmGeneratedFileStream file(planPath);
    file.SetCopyIfDifferent(true);
    for (auto const& o : outs) {
      file << o << '\n';
    }
  }
}

std::unique_ptr<cmLocalGenerator> cmGlobalRedoGenerator::CreateLocalGenerator(
  cmMakefile* makefile)
{
  return std::unique_ptr<cmLocalGenerator>(
    cm::make_unique<cmLocalRedoGenerator>(this, makefile));
}

bool cmGlobalRedoGenerator::FindMakeProgram(cmMakefile* mf)
{
  return this->cmGlobalGenerator::FindMakeProgram(mf);
}

std::vector<cmGlobalGenerator::GeneratedMakeCommand>
cmGlobalRedoGenerator::GenerateBuildCommand(
  std::string const& makeProgram, std::string const& /*projectName*/,
  std::string const& /*projectDir*/,
  std::vector<std::string> const& targetNames, std::string const& /*config*/,
  int jobs, bool verbose, cmBuildOptions /*buildOptions*/,
  std::vector<std::string> const& makeOptions, BuildTryCompile /*isInTryCompile*/)
{
  GeneratedMakeCommand makeCommand;
  makeCommand.Add(this->SelectMakeProgram(makeProgram));

  if (jobs > 0) {
    makeCommand.Add("-j");
    makeCommand.Add(std::to_string(jobs));
  }

  // Native options after `--` are passed through directly to redo.
  makeCommand.Add(makeOptions.begin(), makeOptions.end());

  if (verbose) {
    makeCommand.Add("-v");
  }

  if (targetNames.empty()) {
    makeCommand.Add(this->GetAllTargetName());
  } else {
    for (auto const& tname : targetNames) {
      if (!tname.empty()) {
        makeCommand.Add(tname);
      }
    }
  }

  return { std::move(makeCommand) };
}

